### ISSUE TITLE
Statistics on uncracked hashes

### ISSUE THREAD

**Issue by bandrel** [BlackBox-CSP/password-tools#21] opened 2015-10-23 21:32 UTC
Output of statistics of uncracked hashes.  i.e.  top reused hashes, even though we have not cracked it yet.

**Comment by ryman1** [comment] 2015-11-06 18:28
duplicate of issue https://github.com/BlackBox-CSP/password-tools/issues/12

**Closed as completed by ryman1** 2015-11-06 18:28 UTC
Labels: duplicate
